//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     This file is no longer needed for .NET 8 projects.
//     Settings are now managed via SettingsManager.cs which uses XML serialization.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTrack.Properties
{
    // This class is obsolete in .NET 8+ projects
    // Use SettingsManager.cs instead
}
